android.useAndroidX=true
android.enableJetifier=false
# Increase heap size for the Gradle daemon
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
# Disable parallel execution to save memory if needed
org.gradle.parallel=false
org.gradle.caching=true
# Increase memory for the Kotlin compiler daemon
kotlin.daemon.jvmargs=-Xmx2g
# Optimization for resource namespacing
android.nonTransitiveRClass=true
